name: Check links
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: check-links
        uses: tcort/github-action-markdown-link-check@e047c5b37f24ab722bbef1a27b6fab7f96bc4068 # v1
        with:
          check-modified-files-only: yes
          base-branch: main
          config-file: .github/workflows/markdown-link-check-config.json
